export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  SALES: 'SALES',
  SALES_MANAGER: 'SALES_MANAGER',
  PRODUCTION: 'PRODUCTION',
  PRODUCTION_MANAGER: 'PRODUCTION_MANAGER',
  STORE: 'STORE',
  PROCUREMENT: 'PROCUREMENT',
  PURCHASE_MANAGER: 'PURCHASE_MANAGER',
  QA: 'QA',
  FINANCE: 'FINANCE',
  DISPATCH: 'DISPATCH',
  INSTALLATION: 'INSTALLATION',
  SERVICE_MANAGER: 'SERVICE_MANAGER',
  SERVICE_ENGINEER: 'SERVICE_ENGINEER',
  MANAGEMENT: 'MANAGEMENT'
};

export const PERMISSIONS = {
  // Quotation
  QUOTATION_CREATE: 'quotation.create',
  QUOTATION_EDIT: 'quotation.edit',
  QUOTATION_APPROVE: 'quotation.approve',
  QUOTATION_SEND: 'quotation.send',
  QUOTATION_ACCEPT: 'quotation.accept',
  QUOTATION_REVISE: 'quotation.revise',

  // Product & Pricing
  PRODUCT_CREATE: 'product.create',
  PRODUCT_EDIT: 'product.edit',
  PRODUCT_PRICE_EDIT: 'product.price.edit',
  PRODUCT_DELETE: 'product.delete',

  // Production
  PRODUCTION_CREATE: 'production.create',
  PRODUCTION_PLAN: 'production.plan',
  PRODUCTION_START: 'production.start',
  PRODUCTION_UPDATE: 'production.update',
  PRODUCTION_COMPLETE: 'production.complete',

  // Inventory & Stock
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_ADD: 'inventory.add',
  INVENTORY_ISSUE: 'inventory.issue',
  INVENTORY_ADJUST: 'inventory.adjust',

  // Procurement
  PURCHASE_CREATE: 'purchase.create',
  PURCHASE_APPROVE: 'purchase.approve',
  GRN_CREATE: 'grn.create',

  // Quality
  QA_TEST: 'qa.test',
  QA_APPROVE: 'qa.approve',

  // Billing & Finance
  INVOICE_CREATE: 'invoice.create',
  PAYMENT_VERIFY: 'payment.verify',

  // Dispatch & Logistics
  DISPATCH_CREATE: 'dispatch.create',
  SHIPMENT_UPDATE: 'shipment.update',

  // Installation & Warranty
  INSTALLATION_SCHEDULE: 'installation.schedule',
  INSTALLATION_COMPLETE: 'installation.complete',
  WARRANTY_ACTIVATE: 'warranty.activate',

  // Service
  SERVICE_CREATE: 'service.create',
  SERVICE_ASSIGN: 'service.assign',
  SERVICE_CHECKIN: 'service.checkin',
  SERVICE_DIAGNOSE: 'service.diagnose',
  SERVICE_REPAIR: 'service.repair',
  SERVICE_CLOSE: 'service.close'
};

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: Object.values(PERMISSIONS),
  SALES: [
    PERMISSIONS.QUOTATION_CREATE,
    PERMISSIONS.QUOTATION_EDIT,
    PERMISSIONS.QUOTATION_SEND,
    PERMISSIONS.QUOTATION_REVISE,
    PERMISSIONS.INVENTORY_VIEW
  ],
  SALES_MANAGER: [
    PERMISSIONS.QUOTATION_CREATE,
    PERMISSIONS.QUOTATION_EDIT,
    PERMISSIONS.QUOTATION_APPROVE,
    PERMISSIONS.QUOTATION_SEND,
    PERMISSIONS.QUOTATION_ACCEPT,
    PERMISSIONS.QUOTATION_REVISE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_EDIT
  ],
  PRODUCTION: [
    PERMISSIONS.PRODUCTION_UPDATE,
    PERMISSIONS.INVENTORY_VIEW
  ],
  PRODUCTION_MANAGER: [
    PERMISSIONS.PRODUCTION_CREATE,
    PERMISSIONS.PRODUCTION_PLAN,
    PERMISSIONS.PRODUCTION_START,
    PERMISSIONS.PRODUCTION_UPDATE,
    PERMISSIONS.PRODUCTION_COMPLETE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ISSUE
  ],
  STORE: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADD,
    PERMISSIONS.INVENTORY_ISSUE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.GRN_CREATE
  ],
  PROCUREMENT: [
    PERMISSIONS.PURCHASE_CREATE,
    PERMISSIONS.INVENTORY_VIEW
  ],
  PURCHASE_MANAGER: [
    PERMISSIONS.PURCHASE_CREATE,
    PERMISSIONS.PURCHASE_APPROVE,
    PERMISSIONS.INVENTORY_VIEW
  ],
  QA: [
    PERMISSIONS.QA_TEST,
    PERMISSIONS.QA_APPROVE
  ],
  FINANCE: [
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.PAYMENT_VERIFY,
    PERMISSIONS.PRODUCT_PRICE_EDIT
  ],
  DISPATCH: [
    PERMISSIONS.DISPATCH_CREATE,
    PERMISSIONS.SHIPMENT_UPDATE
  ],
  INSTALLATION: [
    PERMISSIONS.INSTALLATION_SCHEDULE,
    PERMISSIONS.INSTALLATION_COMPLETE,
    PERMISSIONS.WARRANTY_ACTIVATE
  ],
  SERVICE_MANAGER: [
    PERMISSIONS.SERVICE_CREATE,
    PERMISSIONS.SERVICE_ASSIGN,
    PERMISSIONS.SERVICE_CLOSE,
    PERMISSIONS.INVENTORY_VIEW
  ],
  SERVICE_ENGINEER: [
    PERMISSIONS.SERVICE_CHECKIN,
    PERMISSIONS.SERVICE_DIAGNOSE,
    PERMISSIONS.SERVICE_REPAIR,
    PERMISSIONS.INVENTORY_VIEW
  ],
  MANAGEMENT: Object.values(PERMISSIONS)
};

export const COMPANY_PROFILE = {
  name: 'CRYO SCIENTIFIC SYSTEMS PVT LTD',
  tagline: 'Scientific refrigeration & laboratory systems',
  address: 'No. 22, Industrial Estate, Guindy, Chennai, Tamil Nadu 600032, India',
  gstin: '33AABCC1234F1Z5',
  email: 'sales@cryoscientific.com',
  phone: '+91 44 2250 1234',
  website: 'https://cryoscientific.com'
};
